### ISSUE TITLE
Unable to repack file with the plugin

### ISSUE THREAD

**Issue by wrobell** [aparamon/HDF5Plugin-Zstandard#3]
I have tried to use `h5repack` with HDF gzip compressed file

```
$ export HDF5_PLUGIN_PATH=HDF5Plugin-Zstandard
$ h5repack -v -f UD=32015 t1.hdf t2.hdf
```

Unfortunately, the `t2.hdf` file is uncompressed. Do I pass correct parameters?

**Comment by aparamon** [comment]
Ah, you are right!
The problem is in the default
https://github.com/aparamon/HDF5Plugin-Zstandard/blob/7db5d6b78fbd05fc7efa21050616615026c4dc40/zstd_h5plugin.c#L33
which apparently means "no compression".

Does something like 
````
$ h5repack -v -f UD=32015,10 t1.hdf t2.hdf
````
work for you?

**Comment by aparamon** [comment]
It seems that zstd now has negative compression levels, as well as `ZSTD_CLEVEL_DEFAULT` const: https://github.com/facebook/zstd/issues/1148.
My colleagues with submit a PR shortly.

**Comment by wrobell** [comment]
> Does something like
> 
> ```
> $ h5repack -v -f UD=32015,10 t1.hdf t2.hdf
> ```
> work for you?

It does. Thanks. Just in case, when reading `t2.hdf` file with `h5py`, the `compression` attribute returns `None` for dataset compressed with Zstd. Not sure if that's the plugin or `h5py` problem.
